/**
 * Bundled CRD openAPIV3Schema fallbacks, generated by `node scripts/extract-schemas.mjs`.
 * Used server-side when the cluster cannot serve CRD schemas.
 */
export interface BundledCrdSchema {
  name: string;
  group: string;
  kind: string;
  plural: string;
  scope: "Namespaced" | "Cluster";
  versions: Record<string, object>;
}

// Static loader map so Next.js can bundle the JSON files (no fs at runtime).
// Lazy `require` keeps each ~MB-sized schema out of memory until requested.
const loaders: Record<string, () => BundledCrdSchema> = {
  "agentgatewaybackends.agentgateway.dev": () =>
    require("./bundled/agentgatewaybackends.agentgateway.dev.json"),
  "agentgatewayparameters.agentgateway.dev": () =>
    require("./bundled/agentgatewayparameters.agentgateway.dev.json"),
  "agentgatewaypolicies.agentgateway.dev": () =>
    require("./bundled/agentgatewaypolicies.agentgateway.dev.json"),
  "backendtlspolicies.gateway.networking.k8s.io": () =>
    require("./bundled/backendtlspolicies.gateway.networking.k8s.io.json"),
  "gatewayclasses.gateway.networking.k8s.io": () =>
    require("./bundled/gatewayclasses.gateway.networking.k8s.io.json"),
  "gateways.gateway.networking.k8s.io": () =>
    require("./bundled/gateways.gateway.networking.k8s.io.json"),
  "grpcroutes.gateway.networking.k8s.io": () =>
    require("./bundled/grpcroutes.gateway.networking.k8s.io.json"),
  "httproutes.gateway.networking.k8s.io": () =>
    require("./bundled/httproutes.gateway.networking.k8s.io.json"),
  "listenersets.gateway.networking.k8s.io": () =>
    require("./bundled/listenersets.gateway.networking.k8s.io.json"),
  "referencegrants.gateway.networking.k8s.io": () =>
    require("./bundled/referencegrants.gateway.networking.k8s.io.json"),
  "tlsroutes.gateway.networking.k8s.io": () =>
    require("./bundled/tlsroutes.gateway.networking.k8s.io.json"),
  "enterpriseagentgatewaybackends.enterpriseagentgateway.solo.io": () =>
    require("./bundled/enterpriseagentgatewaybackends.enterpriseagentgateway.solo.io.json"),
  "enterpriseagentgatewaypolicies.enterpriseagentgateway.solo.io": () =>
    require("./bundled/enterpriseagentgatewaypolicies.enterpriseagentgateway.solo.io.json"),
  "enterpriseagentgatewayparameters.enterpriseagentgateway.solo.io": () =>
    require("./bundled/enterpriseagentgatewayparameters.enterpriseagentgateway.solo.io.json"),
  "enterpriselistenersets.enterprise.solo.io": () =>
    require("./bundled/enterpriselistenersets.enterprise.solo.io.json"),
};

export function getBundledSchema(crdName: string): BundledCrdSchema | null {
  const load = loaders[crdName];
  return load ? load() : null;
}
